package com.mvn.cn.entity;

public class PermissionTree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_TREE.ID
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_TREE.NAME
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_TREE.TITLE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_TREE.PID
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_TREE.VALUE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_TREE.ID
     *
     * @return the value of T_PERMISSION_TREE.ID
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_TREE.ID
     *
     * @param id the value for T_PERMISSION_TREE.ID
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_TREE.NAME
     *
     * @return the value of T_PERMISSION_TREE.NAME
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_TREE.NAME
     *
     * @param name the value for T_PERMISSION_TREE.NAME
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_TREE.TITLE
     *
     * @return the value of T_PERMISSION_TREE.TITLE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_TREE.TITLE
     *
     * @param title the value for T_PERMISSION_TREE.TITLE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_TREE.PID
     *
     * @return the value of T_PERMISSION_TREE.PID
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_TREE.PID
     *
     * @param pid the value for T_PERMISSION_TREE.PID
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_TREE.VALUE
     *
     * @return the value of T_PERMISSION_TREE.VALUE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_TREE.VALUE
     *
     * @param value the value for T_PERMISSION_TREE.VALUE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    public void setValue(String value) {
        this.value = value;
    }
}