package com.mvn.cn.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.ID
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.NAME
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.ID_NUM
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    private String idNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.PWD
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.PHONE_NUM
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    private String phoneNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.ID
     *
     * @return the value of SYS_USER.ID
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.ID
     *
     * @param id the value for SYS_USER.ID
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.NAME
     *
     * @return the value of SYS_USER.NAME
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.NAME
     *
     * @param name the value for SYS_USER.NAME
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.ID_NUM
     *
     * @return the value of SYS_USER.ID_NUM
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.ID_NUM
     *
     * @param idNum the value for SYS_USER.ID_NUM
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.PWD
     *
     * @return the value of SYS_USER.PWD
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.PWD
     *
     * @param pwd the value for SYS_USER.PWD
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USER.PHONE_NUM
     *
     * @return the value of SYS_USER.PHONE_NUM
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USER.PHONE_NUM
     *
     * @param phoneNum the value for SYS_USER.PHONE_NUM
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }
}