package com.mvn.cn.mapper.authorization;

import com.mvn.cn.anotation.MyMapper;
import com.mvn.cn.entity.authorization.Role;
import com.mvn.cn.entity.authorization.RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyMapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    int countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    Role selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    int updateByPrimaryKey(Role record);
}