package com.mvn.cn.mapper;

import com.mvn.cn.anotation.MyMapper;
import com.mvn.cn.entity.PermissionTree;
import com.mvn.cn.entity.PermissionTreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyMapper
public interface PermissionTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    int countByExample(PermissionTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    int deleteByExample(PermissionTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    int insert(PermissionTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    int insertSelective(PermissionTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    List<PermissionTree> selectByExample(PermissionTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    PermissionTree selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") PermissionTree record, @Param("example") PermissionTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    int updateByExample(@Param("record") PermissionTree record, @Param("example") PermissionTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    int updateByPrimaryKeySelective(PermissionTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PERMISSION_TREE
     *
     * @mbggenerated Thu Jan 11 17:27:01 CST 2018
     */
    int updateByPrimaryKey(PermissionTree record);
}