package com.mvn.cn.mapper;

import com.mvn.cn.anotation.MyMapper;
import com.mvn.cn.entity.User;
import com.mvn.cn.entity.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
//@MyMapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USER
     *
     * @mbggenerated Thu Jan 11 17:02:43 CST 2018
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);
}