package com.mvn.cn.entity.authorization;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_TAB.ID
     *
     * @mbggenerated Tue Jan 16 14:51:29 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_TAB.NAME
     *
     * @mbggenerated Tue Jan 16 14:51:29 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION_TAB.VALUE
     *
     * @mbggenerated Tue Jan 16 14:51:29 CST 2018
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_TAB.ID
     *
     * @return the value of T_PERMISSION_TAB.ID
     *
     * @mbggenerated Tue Jan 16 14:51:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_TAB.ID
     *
     * @param id the value for T_PERMISSION_TAB.ID
     *
     * @mbggenerated Tue Jan 16 14:51:29 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_TAB.NAME
     *
     * @return the value of T_PERMISSION_TAB.NAME
     *
     * @mbggenerated Tue Jan 16 14:51:29 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_TAB.NAME
     *
     * @param name the value for T_PERMISSION_TAB.NAME
     *
     * @mbggenerated Tue Jan 16 14:51:29 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION_TAB.VALUE
     *
     * @return the value of T_PERMISSION_TAB.VALUE
     *
     * @mbggenerated Tue Jan 16 14:51:29 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION_TAB.VALUE
     *
     * @param value the value for T_PERMISSION_TAB.VALUE
     *
     * @mbggenerated Tue Jan 16 14:51:29 CST 2018
     */
    public void setValue(String value) {
        this.value = value;
    }
}