package com.mvn.cn.entity.authorization;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.ID
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.NAME
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.TYPE
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.DESCRIPTION
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.PARENT
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    private Long parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.LAYERORDER
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    private String layerorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.PROP1
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    private String prop1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.PROP2
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    private String prop2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.PROP3
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    private String prop3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PERMISSION.VALUE
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.ID
     *
     * @return the value of T_PERMISSION.ID
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.ID
     *
     * @param id the value for T_PERMISSION.ID
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.NAME
     *
     * @return the value of T_PERMISSION.NAME
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.NAME
     *
     * @param name the value for T_PERMISSION.NAME
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.TYPE
     *
     * @return the value of T_PERMISSION.TYPE
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.TYPE
     *
     * @param type the value for T_PERMISSION.TYPE
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.DESCRIPTION
     *
     * @return the value of T_PERMISSION.DESCRIPTION
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.DESCRIPTION
     *
     * @param description the value for T_PERMISSION.DESCRIPTION
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.PARENT
     *
     * @return the value of T_PERMISSION.PARENT
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public Long getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.PARENT
     *
     * @param parent the value for T_PERMISSION.PARENT
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public void setParent(Long parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.LAYERORDER
     *
     * @return the value of T_PERMISSION.LAYERORDER
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public String getLayerorder() {
        return layerorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.LAYERORDER
     *
     * @param layerorder the value for T_PERMISSION.LAYERORDER
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public void setLayerorder(String layerorder) {
        this.layerorder = layerorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.PROP1
     *
     * @return the value of T_PERMISSION.PROP1
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public String getProp1() {
        return prop1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.PROP1
     *
     * @param prop1 the value for T_PERMISSION.PROP1
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public void setProp1(String prop1) {
        this.prop1 = prop1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.PROP2
     *
     * @return the value of T_PERMISSION.PROP2
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public String getProp2() {
        return prop2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.PROP2
     *
     * @param prop2 the value for T_PERMISSION.PROP2
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public void setProp2(String prop2) {
        this.prop2 = prop2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.PROP3
     *
     * @return the value of T_PERMISSION.PROP3
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public String getProp3() {
        return prop3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.PROP3
     *
     * @param prop3 the value for T_PERMISSION.PROP3
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public void setProp3(String prop3) {
        this.prop3 = prop3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PERMISSION.VALUE
     *
     * @return the value of T_PERMISSION.VALUE
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PERMISSION.VALUE
     *
     * @param value the value for T_PERMISSION.VALUE
     *
     * @mbggenerated Fri Jan 12 10:32:51 CST 2018
     */
    public void setValue(String value) {
        this.value = value;
    }
}