package com.mvn.cn.entity.authorization;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ID
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.NAME
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ID
     *
     * @return the value of T_ROLE.ID
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ID
     *
     * @param id the value for T_ROLE.ID
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.NAME
     *
     * @return the value of T_ROLE.NAME
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.NAME
     *
     * @param name the value for T_ROLE.NAME
     *
     * @mbggenerated Sun Jan 14 20:56:24 GMT+08:00 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}