package com.mvn.cn.entity.authorization;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ID
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.NAME
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.DESCRIPTION
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ISSYSTEM
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private String issystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ORDERNO
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ENABLED
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ISPUBLIC
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private String ispublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.ROLELEVEL
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private String rolelevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.MAXUSER
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private Long maxuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.RECORDER
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private Long recorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.RECORDDATE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private Date recorddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.PROP1
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private String prop1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.PROP2
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private String prop2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ROLE.PROP3
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    private String prop3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ID
     *
     * @return the value of T_ROLE.ID
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ID
     *
     * @param id the value for T_ROLE.ID
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.NAME
     *
     * @return the value of T_ROLE.NAME
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.NAME
     *
     * @param name the value for T_ROLE.NAME
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.DESCRIPTION
     *
     * @return the value of T_ROLE.DESCRIPTION
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.DESCRIPTION
     *
     * @param description the value for T_ROLE.DESCRIPTION
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ISSYSTEM
     *
     * @return the value of T_ROLE.ISSYSTEM
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getIssystem() {
        return issystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ISSYSTEM
     *
     * @param issystem the value for T_ROLE.ISSYSTEM
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setIssystem(String issystem) {
        this.issystem = issystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ORDERNO
     *
     * @return the value of T_ROLE.ORDERNO
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ORDERNO
     *
     * @param orderno the value for T_ROLE.ORDERNO
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ENABLED
     *
     * @return the value of T_ROLE.ENABLED
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ENABLED
     *
     * @param enabled the value for T_ROLE.ENABLED
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ISPUBLIC
     *
     * @return the value of T_ROLE.ISPUBLIC
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getIspublic() {
        return ispublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ISPUBLIC
     *
     * @param ispublic the value for T_ROLE.ISPUBLIC
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setIspublic(String ispublic) {
        this.ispublic = ispublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.ROLELEVEL
     *
     * @return the value of T_ROLE.ROLELEVEL
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getRolelevel() {
        return rolelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.ROLELEVEL
     *
     * @param rolelevel the value for T_ROLE.ROLELEVEL
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setRolelevel(String rolelevel) {
        this.rolelevel = rolelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.MAXUSER
     *
     * @return the value of T_ROLE.MAXUSER
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public Long getMaxuser() {
        return maxuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.MAXUSER
     *
     * @param maxuser the value for T_ROLE.MAXUSER
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setMaxuser(Long maxuser) {
        this.maxuser = maxuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.RECORDER
     *
     * @return the value of T_ROLE.RECORDER
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public Long getRecorder() {
        return recorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.RECORDER
     *
     * @param recorder the value for T_ROLE.RECORDER
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setRecorder(Long recorder) {
        this.recorder = recorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.RECORDDATE
     *
     * @return the value of T_ROLE.RECORDDATE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public Date getRecorddate() {
        return recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.RECORDDATE
     *
     * @param recorddate the value for T_ROLE.RECORDDATE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setRecorddate(Date recorddate) {
        this.recorddate = recorddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.PROP1
     *
     * @return the value of T_ROLE.PROP1
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getProp1() {
        return prop1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.PROP1
     *
     * @param prop1 the value for T_ROLE.PROP1
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setProp1(String prop1) {
        this.prop1 = prop1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.PROP2
     *
     * @return the value of T_ROLE.PROP2
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getProp2() {
        return prop2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.PROP2
     *
     * @param prop2 the value for T_ROLE.PROP2
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setProp2(String prop2) {
        this.prop2 = prop2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ROLE.PROP3
     *
     * @return the value of T_ROLE.PROP3
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getProp3() {
        return prop3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ROLE.PROP3
     *
     * @param prop3 the value for T_ROLE.PROP3
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setProp3(String prop3) {
        this.prop3 = prop3;
    }
}