package com.mvn.cn.entity.authorization;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public RoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andIssystemIsNull() {
            addCriterion("ISSYSTEM is null");
            return (Criteria) this;
        }

        public Criteria andIssystemIsNotNull() {
            addCriterion("ISSYSTEM is not null");
            return (Criteria) this;
        }

        public Criteria andIssystemEqualTo(String value) {
            addCriterion("ISSYSTEM =", value, "issystem");
            return (Criteria) this;
        }

        public Criteria andIssystemNotEqualTo(String value) {
            addCriterion("ISSYSTEM <>", value, "issystem");
            return (Criteria) this;
        }

        public Criteria andIssystemGreaterThan(String value) {
            addCriterion("ISSYSTEM >", value, "issystem");
            return (Criteria) this;
        }

        public Criteria andIssystemGreaterThanOrEqualTo(String value) {
            addCriterion("ISSYSTEM >=", value, "issystem");
            return (Criteria) this;
        }

        public Criteria andIssystemLessThan(String value) {
            addCriterion("ISSYSTEM <", value, "issystem");
            return (Criteria) this;
        }

        public Criteria andIssystemLessThanOrEqualTo(String value) {
            addCriterion("ISSYSTEM <=", value, "issystem");
            return (Criteria) this;
        }

        public Criteria andIssystemLike(String value) {
            addCriterion("ISSYSTEM like", value, "issystem");
            return (Criteria) this;
        }

        public Criteria andIssystemNotLike(String value) {
            addCriterion("ISSYSTEM not like", value, "issystem");
            return (Criteria) this;
        }

        public Criteria andIssystemIn(List<String> values) {
            addCriterion("ISSYSTEM in", values, "issystem");
            return (Criteria) this;
        }

        public Criteria andIssystemNotIn(List<String> values) {
            addCriterion("ISSYSTEM not in", values, "issystem");
            return (Criteria) this;
        }

        public Criteria andIssystemBetween(String value1, String value2) {
            addCriterion("ISSYSTEM between", value1, value2, "issystem");
            return (Criteria) this;
        }

        public Criteria andIssystemNotBetween(String value1, String value2) {
            addCriterion("ISSYSTEM not between", value1, value2, "issystem");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNull() {
            addCriterion("ORDERNO is null");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNotNull() {
            addCriterion("ORDERNO is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernoEqualTo(String value) {
            addCriterion("ORDERNO =", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotEqualTo(String value) {
            addCriterion("ORDERNO <>", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThan(String value) {
            addCriterion("ORDERNO >", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThanOrEqualTo(String value) {
            addCriterion("ORDERNO >=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThan(String value) {
            addCriterion("ORDERNO <", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThanOrEqualTo(String value) {
            addCriterion("ORDERNO <=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLike(String value) {
            addCriterion("ORDERNO like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotLike(String value) {
            addCriterion("ORDERNO not like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoIn(List<String> values) {
            addCriterion("ORDERNO in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotIn(List<String> values) {
            addCriterion("ORDERNO not in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoBetween(String value1, String value2) {
            addCriterion("ORDERNO between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotBetween(String value1, String value2) {
            addCriterion("ORDERNO not between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("ENABLED is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("ENABLED is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(String value) {
            addCriterion("ENABLED =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(String value) {
            addCriterion("ENABLED <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(String value) {
            addCriterion("ENABLED >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(String value) {
            addCriterion("ENABLED >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(String value) {
            addCriterion("ENABLED <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(String value) {
            addCriterion("ENABLED <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLike(String value) {
            addCriterion("ENABLED like", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotLike(String value) {
            addCriterion("ENABLED not like", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<String> values) {
            addCriterion("ENABLED in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<String> values) {
            addCriterion("ENABLED not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(String value1, String value2) {
            addCriterion("ENABLED between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(String value1, String value2) {
            addCriterion("ENABLED not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andIspublicIsNull() {
            addCriterion("ISPUBLIC is null");
            return (Criteria) this;
        }

        public Criteria andIspublicIsNotNull() {
            addCriterion("ISPUBLIC is not null");
            return (Criteria) this;
        }

        public Criteria andIspublicEqualTo(String value) {
            addCriterion("ISPUBLIC =", value, "ispublic");
            return (Criteria) this;
        }

        public Criteria andIspublicNotEqualTo(String value) {
            addCriterion("ISPUBLIC <>", value, "ispublic");
            return (Criteria) this;
        }

        public Criteria andIspublicGreaterThan(String value) {
            addCriterion("ISPUBLIC >", value, "ispublic");
            return (Criteria) this;
        }

        public Criteria andIspublicGreaterThanOrEqualTo(String value) {
            addCriterion("ISPUBLIC >=", value, "ispublic");
            return (Criteria) this;
        }

        public Criteria andIspublicLessThan(String value) {
            addCriterion("ISPUBLIC <", value, "ispublic");
            return (Criteria) this;
        }

        public Criteria andIspublicLessThanOrEqualTo(String value) {
            addCriterion("ISPUBLIC <=", value, "ispublic");
            return (Criteria) this;
        }

        public Criteria andIspublicLike(String value) {
            addCriterion("ISPUBLIC like", value, "ispublic");
            return (Criteria) this;
        }

        public Criteria andIspublicNotLike(String value) {
            addCriterion("ISPUBLIC not like", value, "ispublic");
            return (Criteria) this;
        }

        public Criteria andIspublicIn(List<String> values) {
            addCriterion("ISPUBLIC in", values, "ispublic");
            return (Criteria) this;
        }

        public Criteria andIspublicNotIn(List<String> values) {
            addCriterion("ISPUBLIC not in", values, "ispublic");
            return (Criteria) this;
        }

        public Criteria andIspublicBetween(String value1, String value2) {
            addCriterion("ISPUBLIC between", value1, value2, "ispublic");
            return (Criteria) this;
        }

        public Criteria andIspublicNotBetween(String value1, String value2) {
            addCriterion("ISPUBLIC not between", value1, value2, "ispublic");
            return (Criteria) this;
        }

        public Criteria andRolelevelIsNull() {
            addCriterion("ROLELEVEL is null");
            return (Criteria) this;
        }

        public Criteria andRolelevelIsNotNull() {
            addCriterion("ROLELEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andRolelevelEqualTo(String value) {
            addCriterion("ROLELEVEL =", value, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andRolelevelNotEqualTo(String value) {
            addCriterion("ROLELEVEL <>", value, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andRolelevelGreaterThan(String value) {
            addCriterion("ROLELEVEL >", value, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andRolelevelGreaterThanOrEqualTo(String value) {
            addCriterion("ROLELEVEL >=", value, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andRolelevelLessThan(String value) {
            addCriterion("ROLELEVEL <", value, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andRolelevelLessThanOrEqualTo(String value) {
            addCriterion("ROLELEVEL <=", value, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andRolelevelLike(String value) {
            addCriterion("ROLELEVEL like", value, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andRolelevelNotLike(String value) {
            addCriterion("ROLELEVEL not like", value, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andRolelevelIn(List<String> values) {
            addCriterion("ROLELEVEL in", values, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andRolelevelNotIn(List<String> values) {
            addCriterion("ROLELEVEL not in", values, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andRolelevelBetween(String value1, String value2) {
            addCriterion("ROLELEVEL between", value1, value2, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andRolelevelNotBetween(String value1, String value2) {
            addCriterion("ROLELEVEL not between", value1, value2, "rolelevel");
            return (Criteria) this;
        }

        public Criteria andMaxuserIsNull() {
            addCriterion("MAXUSER is null");
            return (Criteria) this;
        }

        public Criteria andMaxuserIsNotNull() {
            addCriterion("MAXUSER is not null");
            return (Criteria) this;
        }

        public Criteria andMaxuserEqualTo(Long value) {
            addCriterion("MAXUSER =", value, "maxuser");
            return (Criteria) this;
        }

        public Criteria andMaxuserNotEqualTo(Long value) {
            addCriterion("MAXUSER <>", value, "maxuser");
            return (Criteria) this;
        }

        public Criteria andMaxuserGreaterThan(Long value) {
            addCriterion("MAXUSER >", value, "maxuser");
            return (Criteria) this;
        }

        public Criteria andMaxuserGreaterThanOrEqualTo(Long value) {
            addCriterion("MAXUSER >=", value, "maxuser");
            return (Criteria) this;
        }

        public Criteria andMaxuserLessThan(Long value) {
            addCriterion("MAXUSER <", value, "maxuser");
            return (Criteria) this;
        }

        public Criteria andMaxuserLessThanOrEqualTo(Long value) {
            addCriterion("MAXUSER <=", value, "maxuser");
            return (Criteria) this;
        }

        public Criteria andMaxuserIn(List<Long> values) {
            addCriterion("MAXUSER in", values, "maxuser");
            return (Criteria) this;
        }

        public Criteria andMaxuserNotIn(List<Long> values) {
            addCriterion("MAXUSER not in", values, "maxuser");
            return (Criteria) this;
        }

        public Criteria andMaxuserBetween(Long value1, Long value2) {
            addCriterion("MAXUSER between", value1, value2, "maxuser");
            return (Criteria) this;
        }

        public Criteria andMaxuserNotBetween(Long value1, Long value2) {
            addCriterion("MAXUSER not between", value1, value2, "maxuser");
            return (Criteria) this;
        }

        public Criteria andRecorderIsNull() {
            addCriterion("RECORDER is null");
            return (Criteria) this;
        }

        public Criteria andRecorderIsNotNull() {
            addCriterion("RECORDER is not null");
            return (Criteria) this;
        }

        public Criteria andRecorderEqualTo(Long value) {
            addCriterion("RECORDER =", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderNotEqualTo(Long value) {
            addCriterion("RECORDER <>", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderGreaterThan(Long value) {
            addCriterion("RECORDER >", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderGreaterThanOrEqualTo(Long value) {
            addCriterion("RECORDER >=", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderLessThan(Long value) {
            addCriterion("RECORDER <", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderLessThanOrEqualTo(Long value) {
            addCriterion("RECORDER <=", value, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderIn(List<Long> values) {
            addCriterion("RECORDER in", values, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderNotIn(List<Long> values) {
            addCriterion("RECORDER not in", values, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderBetween(Long value1, Long value2) {
            addCriterion("RECORDER between", value1, value2, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorderNotBetween(Long value1, Long value2) {
            addCriterion("RECORDER not between", value1, value2, "recorder");
            return (Criteria) this;
        }

        public Criteria andRecorddateIsNull() {
            addCriterion("RECORDDATE is null");
            return (Criteria) this;
        }

        public Criteria andRecorddateIsNotNull() {
            addCriterion("RECORDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andRecorddateEqualTo(Date value) {
            addCriterion("RECORDDATE =", value, "recorddate");
            return (Criteria) this;
        }

        public Criteria andRecorddateNotEqualTo(Date value) {
            addCriterion("RECORDDATE <>", value, "recorddate");
            return (Criteria) this;
        }

        public Criteria andRecorddateGreaterThan(Date value) {
            addCriterion("RECORDDATE >", value, "recorddate");
            return (Criteria) this;
        }

        public Criteria andRecorddateGreaterThanOrEqualTo(Date value) {
            addCriterion("RECORDDATE >=", value, "recorddate");
            return (Criteria) this;
        }

        public Criteria andRecorddateLessThan(Date value) {
            addCriterion("RECORDDATE <", value, "recorddate");
            return (Criteria) this;
        }

        public Criteria andRecorddateLessThanOrEqualTo(Date value) {
            addCriterion("RECORDDATE <=", value, "recorddate");
            return (Criteria) this;
        }

        public Criteria andRecorddateIn(List<Date> values) {
            addCriterion("RECORDDATE in", values, "recorddate");
            return (Criteria) this;
        }

        public Criteria andRecorddateNotIn(List<Date> values) {
            addCriterion("RECORDDATE not in", values, "recorddate");
            return (Criteria) this;
        }

        public Criteria andRecorddateBetween(Date value1, Date value2) {
            addCriterion("RECORDDATE between", value1, value2, "recorddate");
            return (Criteria) this;
        }

        public Criteria andRecorddateNotBetween(Date value1, Date value2) {
            addCriterion("RECORDDATE not between", value1, value2, "recorddate");
            return (Criteria) this;
        }

        public Criteria andProp1IsNull() {
            addCriterion("PROP1 is null");
            return (Criteria) this;
        }

        public Criteria andProp1IsNotNull() {
            addCriterion("PROP1 is not null");
            return (Criteria) this;
        }

        public Criteria andProp1EqualTo(String value) {
            addCriterion("PROP1 =", value, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp1NotEqualTo(String value) {
            addCriterion("PROP1 <>", value, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp1GreaterThan(String value) {
            addCriterion("PROP1 >", value, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp1GreaterThanOrEqualTo(String value) {
            addCriterion("PROP1 >=", value, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp1LessThan(String value) {
            addCriterion("PROP1 <", value, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp1LessThanOrEqualTo(String value) {
            addCriterion("PROP1 <=", value, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp1Like(String value) {
            addCriterion("PROP1 like", value, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp1NotLike(String value) {
            addCriterion("PROP1 not like", value, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp1In(List<String> values) {
            addCriterion("PROP1 in", values, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp1NotIn(List<String> values) {
            addCriterion("PROP1 not in", values, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp1Between(String value1, String value2) {
            addCriterion("PROP1 between", value1, value2, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp1NotBetween(String value1, String value2) {
            addCriterion("PROP1 not between", value1, value2, "prop1");
            return (Criteria) this;
        }

        public Criteria andProp2IsNull() {
            addCriterion("PROP2 is null");
            return (Criteria) this;
        }

        public Criteria andProp2IsNotNull() {
            addCriterion("PROP2 is not null");
            return (Criteria) this;
        }

        public Criteria andProp2EqualTo(String value) {
            addCriterion("PROP2 =", value, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp2NotEqualTo(String value) {
            addCriterion("PROP2 <>", value, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp2GreaterThan(String value) {
            addCriterion("PROP2 >", value, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp2GreaterThanOrEqualTo(String value) {
            addCriterion("PROP2 >=", value, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp2LessThan(String value) {
            addCriterion("PROP2 <", value, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp2LessThanOrEqualTo(String value) {
            addCriterion("PROP2 <=", value, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp2Like(String value) {
            addCriterion("PROP2 like", value, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp2NotLike(String value) {
            addCriterion("PROP2 not like", value, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp2In(List<String> values) {
            addCriterion("PROP2 in", values, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp2NotIn(List<String> values) {
            addCriterion("PROP2 not in", values, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp2Between(String value1, String value2) {
            addCriterion("PROP2 between", value1, value2, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp2NotBetween(String value1, String value2) {
            addCriterion("PROP2 not between", value1, value2, "prop2");
            return (Criteria) this;
        }

        public Criteria andProp3IsNull() {
            addCriterion("PROP3 is null");
            return (Criteria) this;
        }

        public Criteria andProp3IsNotNull() {
            addCriterion("PROP3 is not null");
            return (Criteria) this;
        }

        public Criteria andProp3EqualTo(String value) {
            addCriterion("PROP3 =", value, "prop3");
            return (Criteria) this;
        }

        public Criteria andProp3NotEqualTo(String value) {
            addCriterion("PROP3 <>", value, "prop3");
            return (Criteria) this;
        }

        public Criteria andProp3GreaterThan(String value) {
            addCriterion("PROP3 >", value, "prop3");
            return (Criteria) this;
        }

        public Criteria andProp3GreaterThanOrEqualTo(String value) {
            addCriterion("PROP3 >=", value, "prop3");
            return (Criteria) this;
        }

        public Criteria andProp3LessThan(String value) {
            addCriterion("PROP3 <", value, "prop3");
            return (Criteria) this;
        }

        public Criteria andProp3LessThanOrEqualTo(String value) {
            addCriterion("PROP3 <=", value, "prop3");
            return (Criteria) this;
        }

        public Criteria andProp3Like(String value) {
            addCriterion("PROP3 like", value, "prop3");
            return (Criteria) this;
        }

        public Criteria andProp3NotLike(String value) {
            addCriterion("PROP3 not like", value, "prop3");
            return (Criteria) this;
        }

        public Criteria andProp3In(List<String> values) {
            addCriterion("PROP3 in", values, "prop3");
            return (Criteria) this;
        }

        public Criteria andProp3NotIn(List<String> values) {
            addCriterion("PROP3 not in", values, "prop3");
            return (Criteria) this;
        }

        public Criteria andProp3Between(String value1, String value2) {
            addCriterion("PROP3 between", value1, value2, "prop3");
            return (Criteria) this;
        }

        public Criteria andProp3NotBetween(String value1, String value2) {
            addCriterion("PROP3 not between", value1, value2, "prop3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ROLE
     *
     * @mbggenerated do_not_delete_during_merge Fri Jan 12 10:32:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ROLE
     *
     * @mbggenerated Fri Jan 12 10:32:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}