package com.mvn.cn.entity.authorization;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE_TAB.ID
     *
     * @mbggenerated Tue Jan 16 15:43:44 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE_TAB.U_ID
     *
     * @mbggenerated Tue Jan 16 15:43:44 CST 2018
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE_TAB.R_ID
     *
     * @mbggenerated Tue Jan 16 15:43:44 CST 2018
     */
    private String rId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE_TAB.ID
     *
     * @return the value of T_USER_ROLE_TAB.ID
     *
     * @mbggenerated Tue Jan 16 15:43:44 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE_TAB.ID
     *
     * @param id the value for T_USER_ROLE_TAB.ID
     *
     * @mbggenerated Tue Jan 16 15:43:44 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE_TAB.U_ID
     *
     * @return the value of T_USER_ROLE_TAB.U_ID
     *
     * @mbggenerated Tue Jan 16 15:43:44 CST 2018
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE_TAB.U_ID
     *
     * @param uId the value for T_USER_ROLE_TAB.U_ID
     *
     * @mbggenerated Tue Jan 16 15:43:44 CST 2018
     */
    public void setuId(String uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE_TAB.R_ID
     *
     * @return the value of T_USER_ROLE_TAB.R_ID
     *
     * @mbggenerated Tue Jan 16 15:43:44 CST 2018
     */
    public String getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE_TAB.R_ID
     *
     * @param rId the value for T_USER_ROLE_TAB.R_ID
     *
     * @mbggenerated Tue Jan 16 15:43:44 CST 2018
     */
    public void setrId(String rId) {
        this.rId = rId;
    }
}